### PR TITLE
fix members

### PR DESCRIPTION
**Pull request by urbanishimwe**
#### What does this PR do?
- fix routing and members issues
#### Description of Task to be completed?
This is both the fix and improvement to the feature [members dummy](https://github.com/rwandaopensource/opensource.org.rw/pull/4)
#### How should this be manually tested?
Navigate to `/members` after cloning both the frontend and the backend part
#### Any background context you want to provide?
this PR depends [on another PR from the backend](https://github.com/rwandaopensource/backend.opensource.org.rw/pull/11)
#### Screenshots (if appropriate)
image
image
#### Questions:
N/A

### CODE REVIEW

**Comment by knowbee** [comment]
Looking at screenshots, it looks like cards are not responsive and it is not pretty, i think you should set a max-height property on the card component to fix that.

**Comment by urbanishimwe** [comment]
> Looking at screenshots, it looks like cards are not responsive and it is not pretty, i think you should set a max-height property on the card component to fix that.

Thank @knowbee ; clear to avoid I'm looking forward to using may be Icons

**Comment by knowbee** [comment]
> > Looking at screenshots, it looks like cards are not responsive and it is not pretty, i think you should set a max-height property on the card component to fix that.
> 
> Thank @knowbee ; clear to avoid I'm looking forward to using may be Icons

A better approach would be replacing the bio with contributions stats and number of public repositories of the user so that it's static as for some users there is no bio..see the mock up below
Members

**Comment by knowbee** [comment]
LGTM

**Review by knowbee — APPROVED** [review]

**Pull request merged**
